runtime: python27
api_version: 1
threadsafe: true
service: default

handlers:
- url: /.*
  script: main.app

env_variables:
  GAE_USE_SOCKETS_HTTPLIB : 'true'
  GOOGLE_CLOUD_PROJECT : "celtic-bivouac-307316"
